version: '3.8'
services:
  web:
    build: .
    command: python ./color_battle/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.dev.env
    depends_on:
      - db
    volumes:
      - ./color_battle:/usr/src/web/color_battle
  db:
    image: postgres
    restart: always
    env_file:
      - ./.dev.env
    volumes:
      - db_volume:/var/lib/postgres/
volumes:
  db_volume: