version: '3.8'
services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    command: python ./color_battle/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.dev.env
    depends_on:
      - db
      - redis
    volumes:
      - ./color_battle:/usr/src/web/color_battle
  web_ws:
    build: .
    command: bash -c "cd ./color_battle && uvicorn --host 0.0.0.0 --port 8001 --reload color_battle.asgi:application "
    restart: always
    env_file:
      - ./.dev.env
    depends_on:
      - web
    volumes:
      - ./color_battle:/usr/src/web/color_battle
  web_game_map:
    build: ./GameMap
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
    restart: always
    env_file:
      - ./.dev.env
    # volumes:
    #   - static_files:/usr/src/web/static_files
  db:
    image: postgres
    restart: always
    env_file:
      - ./.dev.env
    volumes:
      - db_volume:/var/lib/postgres/
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
      - db
      - web_ws
    volumes:
      - ./logs/nginx/:/var/log/nginx
  redis:
    image: redis
    volumes:
      - redis_db:/opt/redis/data

volumes:
  db_volume:
  redis_db: